//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANIMAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANIMAL()
        {
            this.ORDONNANCE = new HashSet<ORDONNANCE>();
            this.HISTORIQUEMALADIE = new HashSet<HISTORIQUEMALADIE>();
        }
    
        public short IDANIMAL { get; set; }
        public Nullable<short> IDCLIENT { get; set; }
        public string NOMESPECE { get; set; }
        public string NOMRACE { get; set; }
        public string NOMANIMAL { get; set; }
        public Nullable<System.DateTime> DATENAISSANCE { get; set; }
        public short TAILLE { get; set; }
        public decimal POIDS { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDONNANCE> ORDONNANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIQUEMALADIE> HISTORIQUEMALADIE { get; set; }
    }
}
