//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PT4_PLANNIMAUX_S4p2B_JKVBLBEntities : DbContext
    {
        public PT4_PLANNIMAUX_S4p2B_JKVBLBEntities()
            : base("name=PT4_PLANNIMAUX_S4p2B_JKVBLBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANIMAL> ANIMAL { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<CONGÉ> CONGÉ { get; set; }
        public virtual DbSet<FACTURE> FACTURE { get; set; }
        public virtual DbSet<HISTORIQUEMALADIE> HISTORIQUEMALADIE { get; set; }
        public virtual DbSet<MALADIE> MALADIE { get; set; }
        public virtual DbSet<ORDONNANCE> ORDONNANCE { get; set; }
        public virtual DbSet<PRODUIT> PRODUIT { get; set; }
        public virtual DbSet<PRODUIT_VENDU> PRODUIT_VENDU { get; set; }
        public virtual DbSet<RENDEZVOUS> RENDEZVOUS { get; set; }
        public virtual DbSet<SALARIÉ> SALARIÉ { get; set; }
        public virtual DbSet<SOIN> SOIN { get; set; }
    }
}
