//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDONNANCE
    {
        public short ID { get; set; }
        public short IDANIMAL { get; set; }
        public short ID_CONCERNE { get; set; }
        public System.DateTime DATEORDO { get; set; }
    
        public virtual ANIMAL ANIMAL { get; set; }
        public virtual SOIN SOIN { get; set; }
    }
}
