//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT4
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUIT()
        {
            this.PRODUIT_VENDU = new HashSet<PRODUIT_VENDU>();
            this.SOIN = new HashSet<SOIN>();
        }
    
        public short IDPRODUIT { get; set; }
        public short QUANTITEENSTOCK { get; set; }
        public string NOMPRODUIT { get; set; }
        public Nullable<decimal> PRIXDEVENTE { get; set; }
        public decimal PRIXACHAT { get; set; }
        public bool MEDICAMENT { get; set; }
        public string DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUIT_VENDU> PRODUIT_VENDU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOIN> SOIN { get; set; }
    }
}
