//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT4
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT_VENDU
    {
        public short IDFACTURE { get; set; }
        public short IDPRODUIT { get; set; }
        public short QUANTITÉ { get; set; }
    
        public virtual FACTURE FACTURE { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
